# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0002_auto_20170912_0443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='xlesson',
            options={'ordering': ['course', 'lesson_name', 'paragraph'], 'verbose_name': 'xlesson', 'verbose_name_plural': 'xlesson'},
        ),
        migrations.AlterField(
            model_name='xblockkey',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highlight.Xlesson'),
        ),
    ]
