# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('highlight', '0003_auto_20170912_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xblockkey',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='highlight.Xlesson'),
        ),
    ]
